# Generated by Django 3.0 on 2020-09-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200916_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minorder',
            field=models.IntegerField(blank=True, default=None, help_text='Minum Products that want to sell on per order', null=True),
        ),
    ]
