# Generated by Django 3.0 on 2020-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200918_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('IN-STOCK', 'IN-STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], default='IN-STOCK', max_length=150, null=True),
        ),
    ]
